### ISSUE TITLE
Will not compile on Linux 4.15

### ISSUE THREAD

**Issue by Eb-** [aramg/droidcam#7]
Droidcam will not compile on Linux 4.15 as the included v4l2loopback module does not use the new kernal timer API.

-------------------------
$ ./install
make -C /lib/modules/\`uname -r\`/build M=\`pwd\`
make[1]: Entering directory '/usr/lib/modules/4.15.2-1-vfio/build'
  CC [M]  /tmp/makepkg/droidcam/src/droidcam/v4l2loopback/v4l2loopback-dc.o
/tmp/makepkg/droidcam/src/droidcam/v4l2loopback/v4l2loopback-dc.c: In function ‘v4l2_loopback_init’:
/tmp/makepkg/droidcam/src/droidcam/v4l2loopback/v4l2loopback-dc.c:2229:3: error: implicit declaration of function ‘setup_timer’; did you mean ‘setup_irq’? [-Werror=implicit-function-declaration]
   setup_timer(&dev->sustain_timer, sustain_timer_clb, nr);
   ^~~~~~~~~~~
   setup_irq
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:323: /tmp/makepkg/droidcam/src/droidcam/v4l2loopback/v4l2loopback-dc.o] Error 1
make[1]: *** [Makefile:1508: _module_/tmp/makepkg/droidcam/src/droidcam/v4l2loopback] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.15.2-1-vfio/build'
make: *** [Makefile:4: all] Error 2

**Comment by aramg** [comment]
Thanks for the report, looking into this.

**Comment by aramg** [comment]
Untested changed pushed to dev
https://github.com/aramg/droidcam/commit/216db9186560ab14f72991c68309ae3ca5eba0d0

**Comment by aramg** [comment]
Download packages updated.
20166fd23adfc826e26952d0837a2df1  droidcam-32bit.tar.bz2
525718dab42ad5868a67844736bd3c6c  droidcam-64bit.tar.bz2
